name: GitHub Release Only

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # Needed to create releases and tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release (GitHub only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --branches main --plugins @semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/github
